name: Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      # - name: Install dependencies
      #   run: yarn install

      # - name: Build
      #   run: yarn run build

      # - name: Install Sass
      #   run: yarn install -g sass

      # - name: Generate your content
      #   run: sass --watch

      - name: Deploy
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          # target-branch: gh-pages
          source-directory: ./html
